name: Android APK Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  ANDROID_HOME: ${{ github.workspace }}/android-sdk
  ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx1536m"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Install basic tools
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip

    - name: Install Android command-line tools & SDK
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        cd $ANDROID_HOME/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /tmp/cmdline-tools.zip
        unzip -q /tmp/cmdline-tools.zip -d .
        mv cmdline-tools latest
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - name: Ensure gradlew executable
      run: |
        cd android_app
        chmod +x ./gradlew

    - name: Inject latest ngrok URL into MainActivity.java
      run: |
        if [ -f /content/drive/MyDrive/JarvisProject/public_url.txt ]; then
          NGROK_URL=$(cat /content/drive/MyDrive/JarvisProject/public_url.txt)
        else
          NGROK_URL="http://127.0.0.1:5000"
        fi
        sed -i "s|private static final String BASE_URL = .*|private static final String BASE_URL = \\\"$NGROK_URL\\\";|" android_app/app/src/main/java/com/jarvisproject/MainActivity.java

    - name: Build APK (assembleDebug)
      run: |
        cd android_app
        ./gradlew assembleDebug --no-daemon

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: android_app/app/build/outputs/apk/debug/app-debug.apk

    - name: Create Release and Upload APK
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: "JarvisProject Build #${{ github.run_number }}"
        draft: false
        prerelease: false
        files: android_app/app/build/outputs/apk/debug/app-debug.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
